### PR TITLE
Add missing SortableJS options, make props reactive & some Typescript madness

### PR DESCRIPTION
**Pull request by tennox**
I was missing some props, then realized they are not reactive, and then went into a rabbithole trying to Typescriptify everything...
well, this is the current result, and I will test it a bit until I mark this as non-draft :yum:

### CODE REVIEW

**Comment by tennox** [comment]
Works great - ready for review :)

**Comment by SupertigerDev** [comment]
Very cool, just to be clear, does it not change the existing functionality in any way? are the existing variable names and stuff the same?

**Comment by SupertigerDev** [comment]
Also could you send an example of what you mean by "make props reactive" please, how was it like before, and how is it now after this?

**Comment by tennox** [comment]
Hi! yes, I did not change existing behavior or variable names, my problems were the following:

1. Missing options
I was missing some options that are available for SortableJs, but weren't defined on the component, so I both added them and tried to get TS to catch missing or invalid options - although I totally overengeneered the last part and it might serve to simplify

2. Non-reactive options
As props weren't reactive, changing e.g. disabled state on an already created Sortable was not possible. I needed to be able to control that, and thought I might as well make all sortablejs options reactive

For reference, here's [our code](https://gitlab.com/onezoomin/note3/-/blob/main/src/components/BlockTree.tsx#L298)

**Comment by SupertigerDev** [comment]
I see, very cool 👍 Thanks!

**Comment by SupertigerDev** [comment]
Also updated in npm 🎉

**Comment by tennox** [comment]
Awesome! Thanks a bunch :)
Let me know if there are any issues.

**Comment by SupertigerDev** [comment]
@tennox Hello, I just noticed that there is an issue with something, not sure what is going on.

https://stackblitz.com/edit/github-lujnef?file=src%2FApp.tsx,node_modules%2Fsolid-sortablejs%2Fdist%2Ftypes%2Findex.d.ts

`Could not find a declaration file for module 'sortablejs'. 'stackblitz:/node_modules/sortablejs/Sortable.min.js' implicitly has an 'any' type.`

I cant use any sortableJS options for some reason. well it works, just the intelesense doesnt work

**Comment by tennox** [comment]
Found out @types packages need to be included in dependencies... solved in #3

**Pull request merged**
